namespace Archiver.Core.Models;

/// <summary>
/// What a user-visible Core message says (T-F209). Core fills the English text itself; a frontend
/// renders the code in the user's language. <see cref="None"/> is text Core did not write (an
/// operating-system or .NET exception message, tar.exe's own output), shown as is.
/// </summary>
public enum MessageCode
{
    None = 0,

    // Sources being archived
    SourceNotFound,
    NothingToArchive,
    CannotAccessFile,
    AccessDenied,
    LinkNotArchived,
    FolderLinkNotFollowed,
    ReparsePointNotArchived,
    ArchiveAlreadyExists,
    CannotCreateArchive,
    AccessDeniedCreatingArchive,
    UnexpectedError,
    UnknownArchivingError,
    EntryNameTooLong,
    NotEnoughSpaceToCompress,
    PasswordNotEntered,
    PasswordEmpty,
    PasswordUnsupportedCharacters,
    PasswordTooLong,
    PasswordOnlyForZip,
    CreationFormatBlocked,
    TarCreationDisabled,
    TarCreationFailed,
    TarNameNotRepresentable,
    TarSignatureInvalid,
    TarSignatureVerificationFailed,

    // Archives being extracted, tested or listed
    NotAnArchiveExtract,
    NotAnArchiveTest,
    NotAnArchiveList,
    UnsupportedByZipEngine,
    FormatBlocked,
    TarExtractionDisabled,
    FormatNeedsNewerTar,
    FormatNotSupportedByTar,
    ArchiveFormatNotSupportedByTar,
    NoTestCapability,
    PasswordProtectedExtract,
    PasswordProtectedTest,
    RememberedPasswordDoesNotFit,
    PasswordProtectedBrowse,
    ZipCorrupted,
    CannotExtractArchive,
    AccessDeniedExtractingArchive,
    CannotReadArchive,
    EntryNameCollision,
    EntryFailed,
    EntryWrongPassword,
    EntryAuthenticationFailed,
    EntryUnsupportedEncryptedMethod,
    InsufficientDiskSpace,
    ZipBombDeclined,
    TarBombDeclined,
    DestinationFileLocked,
    AllEntriesSkipped,
    UnsafeEntryPath,
    EntryAlternateDataStream,
    EntryReservedName,
    EntryControlCharacters,
    CannotExtractEntry,
    EntryThroughReparsePoint,
    FileExistsAtDestination,
    TarExtractionFailed,
    TarUnsafeEntryPath,
    TarListingInconsistent,
    TarSpecialEntry,
    TarDuplicateCopiesNotExtracted,
    TarSourceNameCollisionNotAdded,
    ListingInconsistent,
    TarUnreadableNames,
    SandboxSetupFailed,
    ArchiveInUse,
    CannotOpenArchive,
    CannotReopenArchive,

    // Hashing
    HashFolderSkipped,
    HashLinkSkipped,
    HashFileChanged,

    // Threat scan
    NoAntivirusRegistered,
    ScanSessionFailed,
    ScanCannotReadArchive,
    ScanCannotReadEntry,
    ScanCannotExtract,
    ScanRemovedOrBlocked,
    ScanEntryFailed,
    ScanEntryIntegrityFailed,
    ScanEntryPasswordProtected,
    ScanEntryWrongPassword,
    ScanEntryUnsupportedMethod,
    ScanEntryAuthenticationFailed,
    ScanEntryTooLarge,
    LocalHeaderMismatch,

    // Error details (T-F297): the English text Windows or Core wrote, kept in every language
    SystemInvalidName,
    SystemAccessDenied,
    SystemSharingViolation,
    SystemDiskFull,
    ContentCrcMismatch,
    ContentLargerThanDeclared,
    ContentSmallerThanDeclared,
    EntryDataTruncated,

    // T-F322: an encrypted 7z or RAR - tar.exe cannot decrypt either, so no password helps
    PasswordProtectedFormatNotSupported,

    // T-F275: PAR2 recovery data
    RecoveryPercentInvalid,
    RecoveryDataDisabled,
    RecoveryDataNotCreated,
    RecoveryDataFileTooLarge,
    RecoveryOldVolumeNotDeleted,
    RecoveryDataDamagedRepairable,
    RecoveryDataDamagedNotRepairable,
    RecoveryDataRepairTooLarge,
    RecoveryDataDoesNotMatch,
    RecoveryDataUnusable,
    RecoveryDataForAnotherFile,
    RecoveryDataTargetNotFound,
    RecoveryDataNameMismatch,
    RecoveryDataNotFound,
    RecoveryDataRepaired,
    RecoveryRepairCheckFailed,
    RecoveryRepairNotWritten,
    RecoveryDataIntact,
}
